modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/IThundxr/DB-Extended/issues"
license = "GNU General Public License v3.0"

[[mods]]
modId = "dbe"
version = "${version}"
displayName = "Dave's Building Extended"
authors = "IThundxr, Rabbitminers, SpaceDave"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "icon.png"

[[dependencies.dbe]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dbe]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"